android on arm - android test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,11 +38,11 @@ jobs:
           command: |
             export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
           background: true
-      - run:
-          # run in parallel with the emulator starting up, to optimize build time
-          name: Run androidTest task
-          command: |
-            ./gradlew --init-script circleci.gradle androidTest
+      # - run:
+      #     # run in parallel with the emulator starting up, to optimize build time
+      #     name: Run androidTest task
+      #     command: |
+      #       ./gradlew --init-script circleci.gradle androidTest
       - run:
           name: Wait for emulator to start
           command: |
@@ -53,30 +53,30 @@ jobs:
             adb shell settings put global window_animation_scale 0.0
             adb shell settings put global transition_animation_scale 0.0
             adb shell settings put global animator_duration_scale 0.0
-      - run:
-          name: Run UI tests (with retry)
-          command: |
-            MAX_TRIES=2
-            run_with_retry() {
-               n=1
-               until [ $n -gt $MAX_TRIES ]
-               do
-                  echo "Starting test attempt $n"
-                  ./gradlew --init-script circleci.gradle androidTest && break
-                  n=$[$n+1]
-                  sleep 5
-               done
-               if [ $n -gt $MAX_TRIES ]; then
-                 echo "Max tries reached ($MAX_TRIES)"
-                 exit 1
-               fi
-            }
-            run_with_retry
-      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
-          path: app/build/reports
-          destination: reports
-      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
-          path: app/build/test-results
+      # - run:
+      #     name: Run UI tests (with retry)
+      #     command: |
+      #       MAX_TRIES=2
+      #       run_with_retry() {
+      #          n=1
+      #          until [ $n -gt $MAX_TRIES ]
+      #          do
+      #             echo "Starting test attempt $n"
+      #             ./gradlew --init-script circleci.gradle androidTest && break
+      #             n=$[$n+1]
+      #             sleep 5
+      #          done
+      #          if [ $n -gt $MAX_TRIES ]; then
+      #            echo "Max tries reached ($MAX_TRIES)"
+      #            exit 1
+      #          fi
+      #       }
+      #       run_with_retry
+      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
+      #     path: app/build/reports
+      #     destination: reports
+      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
+      #     path: app/build/test-results
 
   # ui-tests:
   #   executor:
